"""add barber assignment to bookings

Revision ID: c93d634672a6
Revises: e716367a856b
Create Date: 2026-04-28 15:39:01.948424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c93d634672a6'
down_revision: Union[str, Sequence[str], None] = 'e716367a856b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('barber_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'bookings', 'users', ['barber_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'barber_id')
    # ### end Alembic commands ###
